### ISSUE TITLE
Translit\Translit-1.0.2.lua:68: attempt to index local 'text' (a nil value)

### ISSUE THREAD

**Issue by tordenflesk** [Vardex/Translit#1]
2x Translit\Translit-1.0.2.lua:68: attempt to index local 'text' (a nil value)
Translit\Translit-1.0.2.lua:68: in function <Translit\Translit.lua:65>
[C]: in function `Show'
...rfaceTradeSkillMaster\Private\TooltipLib.lua:310: in function `Show'
...rfaceTradeSkillMaster\Private\TooltipLib.lua:202: in function <...rfaceTradeSkillMaster\Private\TooltipLib.lua:165>
[C]: in function `BattlePetTooltipTemplate_SetBattlePet'
FrameXML\BattlePetTooltip.lua:20: in function <FrameXML\BattlePetTooltip.lua:3>
[C]: in function `BattlePetToolTip_Show'
FrameXML\ContainerFrame.lua:1406: in function `ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
self = TSMExtraTip3 {
 0 = <userdata>
 updateTooltip = 0.200000
 Attach = <function> defined @TradeSkillMaster\Private\TooltipLib.lua:301
 Right = <table> {
 }
 Left = <table> {
 }
 TopOverlay = <unnamed> {
 }
 needsReset = true
 BottomOverlay = <unnamed> {
 }
 Show = <function> defined @TradeSkillMaster\Private\TooltipLib.lua:307
 OnUpdate = <function> defined @TradeSkillMaster\Private\TooltipLib.lua:333
}
(for index) = 7
(for limit) = 9
(for step) = 1
i = 7
text = nil
(*temporary) = "GameTooltipTextLeft7"
(*temporary) = nil
(*temporary) = ""
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = "!"
(*temporary) = "attempt to index local 'text' (a nil value)"
LibTranslit = <table> {
 Transliterate = <function> defined @Translit\Libs\LibTranslit-1.0\LibTranslit-1.0.lua:80
}
options = <table> {
 mark = "!"
 tooltip = true
 chat = true
}

**Comment by Vardex** [comment]
Thanks for your report. Should be fixed with 1.0.3.
